manifest:
  version: "0.13"

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  defaults:
    remote: ncs

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.1.1
      import:
        name-allowlist:
          - zephyr
          - mcuboot
          - nrfxlib
          - mbedtls
          - trusted-firmware-m
          - cmsis
          - cmsis_6
          - hal_nordic
          - matter
          - nrf_wifi
          - openthread
          - mbedtls
          - nrf_security
          - oberon-psa-crypto
          - hostap

  self:
    path: .
